version = 1

[[annotations]]
path = "org.kde.kjar.desktop"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "org.kde.kjar.metainfo.xml"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "README.md"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".flatpak-manifest.json"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"