// SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
// SPDX-FileCopyrightText: 2026 Hadi Chokr <hadichokr@icloud.com>

#include "kjarapp.h"

#include <QCoreApplication>
#include <QDesktopServices>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QProcess>
#include <QThread>
#include <QUrl>

static const QString APP_ID = QStringLiteral("org.kde.kjar");

QString KjarApp::defaultModulesDir()
{
    return QDir::homePath() + QStringLiteral("/.local/share/kjar/modules");
}

QStringList KjarApp::buildJvmArgs(const QString &jarPath) const
{
    const QDir shareDir(QStringLiteral("/app/share"));
    QStringList modulePaths;
    for (const QFileInfo &fi : shareDir.entryInfoList(QDir::Dirs | QDir::NoDotAndDotDot)) {
        modulePaths << fi.absoluteFilePath();
    }
    const QString modulesDir = defaultModulesDir();
    QDir().mkpath(modulesDir);
    modulePaths << modulesDir;

    return {
        QStringLiteral("--module-path"), modulePaths.join(QLatin1Char(':')),
        QStringLiteral("--add-modules"), QStringLiteral("ALL-MODULE-PATH"),
        QStringLiteral("-jar"), jarPath
    };
}

KjarApp::KjarApp(QObject *parent)
: QObject(parent)
, m_targetDir(QDir::homePath() + QStringLiteral("/.local/bin"))
{}

void KjarApp::setBusy(bool busy)
{
    if (m_busy == busy) {
        return;
    }
    m_busy = busy;
    Q_EMIT busyChanged();
}

QStringList KjarApp::availableTools() const
{
    return findAvailableTools();
}

QStringList KjarApp::findAvailableTools() const
{
    QStringList tools;
    const QStringList searchPaths = {
        QStringLiteral("/app/bin"),
        QStringLiteral("/app/jdk/bin")
    };
    for (const QString &path : searchPaths) {
        QDir dir(path);
        if (!dir.exists()) {
            continue;
        }
        for (const QFileInfo &fi : dir.entryInfoList(QDir::Files | QDir::Executable)) {
            if (!fi.isExecutable()) {
                continue;
            }
            const QString name = fi.fileName();
            if (!tools.contains(name)) {
                tools.append(name);
            }
        }
    }
    tools.sort();
    return tools;
}

bool KjarApp::runJarFile(const QString &file)
{
    const QString watcherPath =
    QCoreApplication::applicationDirPath() + QStringLiteral("/kjar_watcher");

    if (!QFile::exists(watcherPath)) {
        Q_EMIT errorOccurred(i18n("Watcher binary not found at %1", watcherPath));
        return false;
    }

    QStringList watcherArgs;
    watcherArgs << file;
    watcherArgs << buildJvmArgs(file);

    if (!QProcess::startDetached(watcherPath, watcherArgs)) {
        Q_EMIT errorOccurred(i18n("Failed to launch watcher for %1", file));
        return false;
    }
    return true;
}

void KjarApp::openModulesFolder()
{
    QDir().mkpath(defaultModulesDir());
    QDesktopServices::openUrl(QUrl::fromLocalFile(defaultModulesDir()));
}

void KjarApp::generateWrappers()
{
    if (m_busy) {
        return;
    }
    setBusy(true);

    QThread *thread = QThread::create([this]() {
        const QStringList tools = findAvailableTools();
        int generated = 0;
        int skipped = 0;

        QProcess mkdirProc;
        mkdirProc.start(QStringLiteral("flatpak-spawn"),
                        { QStringLiteral("--host"), QStringLiteral("mkdir"),
                            QStringLiteral("-p"), m_targetDir });
        mkdirProc.waitForFinished();

        for (const QString &tool : tools) {
            const QString wrapperPath = m_targetDir + QLatin1Char('/') + tool;

            const QString checkScript = QStringLiteral(
                "if [ -f '%1' ] && ! grep -q 'generated by kjar' '%1' 2>/dev/null; "
                "then echo 'skip'; else echo 'ok'; fi"
            ).arg(wrapperPath);

            QProcess checkProcess;
            checkProcess.start(QStringLiteral("flatpak-spawn"),
                               { QStringLiteral("--host"), QStringLiteral("sh"),
                                   QStringLiteral("-c"), checkScript });
            checkProcess.waitForFinished();

            if (QString::fromLocal8Bit(checkProcess.readAllStandardOutput()).trimmed()
                == QLatin1String("skip")) {
                skipped++;
            continue;
                }

                const QString createScript = QStringLiteral(
                    "cat > '%1' <<'EOF'\n"
                    "#!/usr/bin/env sh\n"
                    "# generated by kjar for %2\n"
                    "exec flatpak run --command=%3 %2 \"$@\"\n"
                    "EOF\n"
                    "chmod +x '%1'"
                ).arg(wrapperPath, APP_ID, tool);

                QProcess createProcess;
                createProcess.start(QStringLiteral("flatpak-spawn"),
                                    { QStringLiteral("--host"), QStringLiteral("sh"),
                                        QStringLiteral("-c"), createScript });
                createProcess.waitForFinished();

                if (createProcess.exitCode() == 0) {
                    generated++;
                } else {
                    Q_EMIT errorOccurred(
                        i18n("Failed to create wrapper for %1: %2", tool,
                             QString::fromLocal8Bit(createProcess.readAllStandardError())));
                }
        }

        Q_EMIT operationCompleted(
            i18n("Generated %1 wrappers in %2 (skipped %3 existing non-kjar binaries)",
                 QString::number(generated), m_targetDir, QString::number(skipped)));

        setBusy(false);
    });

    thread->setParent(this);
    connect(thread, &QThread::finished, thread, &QThread::deleteLater);
    thread->start();
}
