// SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
// SPDX-FileCopyrightText: 2026 Hadi Chokr <hadichokr@icloud.com>

#include "kjarapp.h"

#include "kjar.h"

#include <KLocalizedString>

#include <QCoreApplication>
#include <QDesktopServices>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QProcess>
#include <QUrl>

using namespace Qt::Literals::StringLiterals;

namespace
{

constexpr QByteArrayView Marker("generated by kjar");

bool isOurWrapper(const QString &path)
{
    QFile f(path);
    return f.open(QIODevice::ReadOnly) && f.read(256).contains(Marker);
}

} // namespace

KjarApp::KjarApp(QObject *parent)
    : QObject(parent)
{
}

QStringList KjarApp::availableTools() const
{
    return Kjar::jdkTools();
}

QString KjarApp::runJar(const QUrl &url)
{
    const QString path = url.isLocalFile() ? url.toLocalFile() : url.toString();

    if (!QFile::exists(path)) {
        return i18n("%1 does not exist or cannot be accessed.", path);
    }

    // Re-exec ourselves in watcher mode
    const QStringList args{u"--watch"_s, path};
    if (!QProcess::startDetached(Kjar::selfPath(), args)) {
        return i18n("Failed to launch %1.", path);
    }
    return {};
}

void KjarApp::openModulesFolder()
{
    Kjar::ensureUserModulesDir();
    QDesktopServices::openUrl(QUrl::fromLocalFile(Kjar::userModulesDir()));
}

QVariantMap KjarApp::generateWrappers()
{
    const QString dir = Kjar::wrapperDir();
    if (!QDir().mkpath(dir)) {
        return {{u"ok"_s, false}, {u"message"_s, i18n("Could not create %1.", dir)}};
    }

    int written = 0;
    int skipped = 0;

    for (const QString &tool : Kjar::jdkTools()) {
        const QString path = dir + u'/' + tool;

        // Never clobber something we did not write.
        if (QFile::exists(path) && !isOurWrapper(path)) {
            ++skipped;
            continue;
        }

        QFile f(path);
        if (!f.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
            ++skipped;
            continue;
        }

        const QByteArray script = QStringLiteral("#!/usr/bin/env sh\n"
                                                 "# %1 (%2)\n"
                                                 "exec flatpak run %3 %2 \"$@\"\n")
                                      .arg(QString::fromLatin1(Marker), tool, QString::fromLatin1(Kjar::AppId))
                                      .toUtf8();

        // A short write leaves a truncated script that still carries the marker,
        // so the next run would happily overwrite it and report success again.
        if (f.write(script) != script.size() || !f.flush()) {
            f.close();
            f.remove();
            ++skipped;
            continue;
        }
        f.close();

        constexpr QFileDevice::Permissions Mode = QFileDevice::ReadOwner | QFileDevice::WriteOwner | QFileDevice::ExeOwner | QFileDevice::ReadGroup
            | QFileDevice::ExeGroup | QFileDevice::ReadOther | QFileDevice::ExeOther;
        if (!f.setPermissions(Mode)) {
            f.remove();
            ++skipped;
            continue;
        }
        ++written;
    }

    QString message = i18np("Generated %1 wrapper in %2.", "Generated %1 wrappers in %2.", written, dir);
    if (skipped > 0) {
        message += u' ';
        message += i18np("Skipped %1 existing non-kjar file.", "Skipped %1 existing non-kjar files.", skipped);
    }

    return {{u"ok"_s, written > 0}, {u"message"_s, message}};
}

QVariantMap KjarApp::removeWrappers()
{
    const QString dir = Kjar::wrapperDir();

    int removed = 0;
    int failed = 0;

    const QFileInfoList entries = QDir(dir).entryInfoList(QDir::Files, QDir::Name);
    for (const QFileInfo &fi : entries) {
        const QString path = fi.absoluteFilePath();
        if (!isOurWrapper(path)) {
            continue;
        }
        if (QFile::remove(path)) {
            ++removed;
        } else {
            ++failed;
        }
    }

    if (removed == 0 && failed == 0) {
        return {{u"ok"_s, true}, {u"message"_s, i18n("No kjar wrappers found in %1.", dir)}};
    }

    QString message = i18np("Removed %1 wrapper from %2.", "Removed %1 wrappers from %2.", removed, dir);
    if (failed > 0) {
        message += u' ';
        message += i18np("Could not remove %1 file.", "Could not remove %1 files.", failed);
    }

    return {{u"ok"_s, failed == 0}, {u"message"_s, message}};
}
